---
# This playbook will install mysql and create db user and give permissions.

-  name: Install Mysql package
   yum: name={{ item }} state=installed
   with_items:
      - mysql57-server

-  name: Start Mysql Service
   service: name=mysqld state=started enabled=yes

-  name: Create Application DB User
   mysql_user: name={{ dbuser }} password={{ upassword }} priv=*.*:ALL host='%' state=present